# Generated by Django 5.2.17 on 2026-08-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'commune',
                'verbose_name_plural': 'communes',
                'ordering': ['region', 'departement', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Menage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=100, unique=True)),
                ('cle_menage', models.CharField(blank=True, max_length=100)),
                ('nom_chef', models.CharField(max_length=100)),
                ('prenom_chef', models.CharField(max_length=100)),
                ('surnom', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('situation_matrimoniale', models.CharField(blank=True, max_length=50)),
                ('nb_epouses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type_piece', models.CharField(blank=True, max_length=50)),
                ('num_piece', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone_alt', models.CharField(blank=True, max_length=20)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('taille_declaree', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('statut_residence', models.CharField(blank=True, max_length=50)),
                ('score_vulnerabilite', models.FloatField(blank=True, null=True)),
                ('code_enqueteur', models.CharField(blank=True, max_length=50)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('nom_normalise', models.CharField(blank=True, db_index=True, max_length=150)),
                ('prenom_normalise', models.CharField(blank=True, db_index=True, max_length=150)),
                ('cle_blocage', models.CharField(blank=True, db_index=True, max_length=50)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menages', to='registre.commune')),
            ],
            options={
                'verbose_name': 'ménage',
                'verbose_name_plural': 'ménages',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.PositiveSmallIntegerField()),
                ('nom_complet', models.CharField(max_length=150)),
                ('lien_parente', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scolarise', models.BooleanField(blank=True, null=True)),
                ('handicap', models.BooleanField(default=False)),
                ('perimetre_brachial', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oedemes', models.BooleanField(default=False)),
                ('mas', models.BooleanField(default=False, verbose_name='malnutrition aiguë sévère')),
                ('menage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='registre.menage')),
            ],
            options={
                'verbose_name': 'membre',
                'verbose_name_plural': 'membres',
                'ordering': ['menage', 'rang'],
            },
        ),
        migrations.CreateModel(
            name='PaireSuspecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('motifs', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('doublon_confirme', 'Doublon confirmé'), ('menages_distincts', 'Ménages distincts')], default='en_attente', max_length=20)),
                ('arbitre_par', models.CharField(blank=True, max_length=100)),
                ('date_arbitrage', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('menage_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paires_comme_a', to='registre.menage')),
                ('menage_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paires_comme_b', to='registre.menage')),
            ],
            options={
                'verbose_name': 'paire suspecte',
                'verbose_name_plural': 'paires suspectes',
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('menage_a', 'menage_b'), name='paire_couple_unique'), models.CheckConstraint(condition=models.Q(('menage_a__lt', models.F('menage_b'))), name='paire_ordre_menages')],
            },
        ),
    ]
